### ISSUE TITLE
Error in rendering Chords - end of chords messed up

### ISSUE THREAD

**Issue by rjurney** [nicgirault/circosJS#10]
JSFiddle reproduces issue at https://jsfiddle.net/9m5e7wm9/2/

This chord looks funny. It isn't in the right place, and the ends are strange. What can I do?

![image](https://cloud.githubusercontent.com/assets/42149/8814727/c9787b9e-2fc4-11e5-81a1-ed591bdd196d.png)

**Comment by nicgirault** [comment]
Thank you for reporting this bug. It's fixed in version 1.6.2.

**Comment by rjurney** [comment]
You RULE!

On Wednesday, July 22, 2015, nic.girault <notifications@github.com> wrote:

> Closed #10 <https://github.com/nicgirault/circosJS/issues/10>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicgirault/circosJS/issues/10#event-361952492>.
>


-- 
Russell Jurney twitter.com/rjurney russell.jurney@gmail.com datasyndrome.com
