### ISSUE TITLE
Documentation update request

### ISSUE THREAD

**Issue by ultrageek** [nicgirault/circosJS#12]
I love circosJS and have used it several times in college rankings articles for a client. But for the life of me, I cannot figure out how to add tooltips like the ones that appear in the Global Migration chord diagram. I'm using layout, histogram, heatmap, and text in one circular chart, but none have provisions for tooltips. Or at least the documentation does not show that. I'm going to see if I can use D3js to query my objects and bind tooltips, but I wanted to see if there was a simpler way before first. If there is (for at least histogram and heatmap), I'm wondering if you could add something in the documentation to show that. Please and thank you.

**Comment by nicgirault** [comment]
Hi, circosjs does not support tooltip for now. I understand your request. I'll try to release a new version next week with tooltip support.

**Comment by ultrageek** [comment]
Thank, Nic. I was trying to see if I could manually force D3 to add the tooltips, but it's tricky due to lack of HTML node ids, and my client effort does not warrant it so far.

**Comment by ultrageek** [comment]
If the resulting segments of the various tracks in each "circosjs" graph had unique HTML/SVG node IDs, it would not be too hard to use D3 to add user-defined tooltips. But the IDs also have to be user-defined. Without IDs, it is too difficult to add tooltips using HTML classes.

**Comment by pablasimarjot** [comment]
Hi, is there any update on the tool tip feature? It would be very handy. Thanks for all the great work. Keep it up.

**Comment by nicgirault** [comment]
@pablasimarjot the first version of the tooltip is available in version 1.7.0. Your feedbacks are more than welcome

**Comment by pablasimarjot** [comment]
This is such a wonderful addition to CircosJS. Since there are lot of data points to visualize, tool-tips allows users to focus on points of interest. I tried it out and it works very well. With some in-style formatting I was able to get the style I wanted. Thanks a lot @nicgirault .

**Comment by ultrageek** [comment]
Thank you, Nic. I'll test it later this week with a new client visualization and comment. Much thanks for the effort.

**Comment by ultrageek** [comment]
Hi Nic,

In demo.html, there is this following line:

<script src='../bower_components/d3-tip/index.js'></script>

I'm having trouble finding this directory and file. I have to use a CDN url for client reasons, but I downloaded the latest distribution to my Mac and that path does not seem to be there.

**Comment by nicgirault** [comment]
Hi, you've to run the command `bower install d3-tip` or use the CDN `<script src="http://labratrevenge.com/d3-tip/javascripts/d3.tip.v0.6.3.js"></script>
`

**Comment by ultrageek** [comment]
Thanks, Nic. I overlooked bower install because I only used the CDN before, but I didn't see the d3.tip CDN URL. Very excited to see how this works. FYI, If you need some help with examples, I'll try to find some time later this year.

**Comment by ultrageek** [comment]
Okay, I tried out demo.html locally on my Mac and it works and looks great. However, when I replace the relative URL (in demo.html) for circosJS.js with the rawgit CDN URL (https://cdn.rawgit.com/nicgirault/circosJS/master/dist/circosJS.js), it doesn't work.

So despite RawGit.com's claim of an update "within minutes" of a push in GitHub, it does not seem to have updated. However, as my client is now on WPEngine, I can probably use their CDN.
