### ISSUE TITLE
Embedded demos not showing up

### ISSUE THREAD

**Issue by Deleetdk** [nicgirault/circosJS#16]
The embedded demos are not showing up. Sometimes there are Fiddles or similar one can click to see them, but sometimes there are not.

I tried Firefox and Chrome with the same results.

Two examples (from [here](https://nicgirault.gitbooks.io/circosjs/content/tracks/heatmap.html) and [here](https://nicgirault.gitbooks.io/circosjs/content/tracks/chords.html)):
![circosjs embed](https://cloud.githubusercontent.com/assets/6759913/17164869/5eac100a-53cc-11e6-830d-734c4c3c00ca.png)
![circosjs embed2](https://cloud.githubusercontent.com/assets/6759913/17164873/5fad5d6a-53cc-11e6-8deb-06c9653fea66.png)

**Comment by nicgirault** [comment]
Yes thank you for the feedback. I'm working on this issue due to gitbook upgrade

**Comment by nicgirault** [comment]
I fixed it with static images. Thank you again for your feedback
