### ISSUE TITLE
RawGit js file CDN url?

### ISSUE THREAD

**Issue by ultrageek** [nicgirault/circosJS#28]
I just noticed that all of the work I did for a client showing CircosJS charts no longer render. I've used the RawGit CDN URL https://cdn.rawgit.com/nicgirault/circosJS/master/dist/circosJS.js, which points to a file that no longer exists. I tried the URL to "circos.js", which does exist, but the charts still do not render. I have to use a CDN because the client did not give me the ability to upload a JS file for re-use. CDNjs.com does not have the file.

Because the client did not want the charts in newer articles, I have not had reason to go through your revision notes, but maybe you can save me a bit of time by saying whether there have been significant changes in function names? Any suggestions for how I can quickly fix all these CircosJS charts no longer rendering? E.g., is there any archive of the original JS file on RawGit?

Thanks in advance.
-raj

**Comment by nicgirault** [comment]
You should never use this kind of link in production. Instead of this you should at least point to a given commit as this one which is the last one of version 1: https://rawcdn.githack.com/nicgirault/circosJS/77d42d1c3ed95b57a04f48f157cd1d0c4f7d48ad/dist/circosJS.js

**Comment by ultrageek** [comment]
Okay, thanks. I started using your library last January (2016), and I was under the impression that rawgit was preferred. I'll change my content. Cheers

**Comment by winni2k** [comment]
It appears that the template html file linked to on the [README.md](https://github.com/nicgirault/circosJS#installation) uses a rawgit link ('https://cdn.rawgit.com/nicgirault/circosJS/v2/dist/circos.js'), but note the `v2`, which points to a git tag.  If the tag is never moved, then you should be fine...

**Comment by ultrageek** [comment]
The problem is that the client will neither give me FTP access to upload CircosJS files nor upload them for me. So I had to use the RawGit CDN URL(s).
