### ISSUE TITLE
allow es6 import/require

### ISSUE THREAD

**Issue by ppisljar** [nicgirault/circosJS#29]
its not possible to require/import circos ....

in circos.js, add this on the end:

`module.exports = Circos;`

this will allow to import like this:
`import Circos from 'circos/dist/circos'`

to allow direct inclussion add index.js directly in the circos folder with this content: (first change is still needed)
```
module.exports = require('./dist/circos');
```

now its possible to include like 
`import Circos from 'circos';`

**Comment by boomler** [comment]
Yes. It solved my problem.

**Comment by nicgirault** [comment]
Thanks @ppisljar for the feedback. It is now available  for versions 2.0.5+
