### ISSUE TITLE
Control the radius of chords tracks

### ISSUE THREAD

**Issue by YulongNiu** [nicgirault/circosJS#31]
Hi,
 
Thanks for the excellent project.
I would like to know if there a way to control the radius of chords tracks, just like [circos](http://circos.ca/documentation/tutorials/links/rules4/images).

Thanks.

**Comment by nicgirault** [comment]
Hello @YulongNiu thanks for the feedback. I added the option in v2.0.4 and the doc is available here: https://github.com/nicgirault/circosJS#radius
