### ISSUE TITLE
library bundle

### ISSUE THREAD

**Issue by gaitat** [nicgirault/circosJS#34]
I just noticed that the library is pretty big in size because it includes several other libraries. I am not sure how good of a practice this is. On one hand you get everything and you dont have to worry about anything else. On the other hand if a project already includes loadash or d3 it gets everything twice. Maybe a distribution that includes everything and one that does not?

What do other people think?

**Comment by nicgirault** [comment]
@gaitat I would say that the good practice Today is to build you app with webpack or another app bundler. Like this dependencies are not loaded twice. Circos already allows to use it like this. The packaged version is for web developer experts so I'm not sure the size of the librairy is a concern for them. What do you think about it?

**Comment by u-phoria** [comment]
Further to the above, trying to use circos as a library in an app bundled using webpack.

I added circos 2.0.5 as a dependency in package.js - it has the changes referenced in #29 to allow es6 import.

In the webpack entrypoint js file (main.js in my case), I'm doing ```import Circos from 'circos'```.

Then 
```
var myCircos = new Circos({
    ...
});
```

This results in the following error: 
```main.bundle.js:150 Uncaught TypeError: _circos2.default is not a constructor```

Any pointers appreciated.

**Comment by imranariffin** [comment]
@u-phoria ,

I was getting the same thing. I really need clarification on this for I need to integrate circos js to react. Been waiting for response well.

**Comment by nicgirault** [comment]
@u-phoria fiexed in version 2.0.7

**Comment by u-phoria** [comment]
Thanks @nicgirault, appreciated.
