### ISSUE TITLE
How to cite circosJS?

### ISSUE THREAD

**Issue by YulongNiu** [nicgirault/circosJS#35]
Hi @nicgirault 

A nice project. I used the circosJS in my project and will publish a paper. Could you please inform me the appropriate way to cite circosJS? Thanks!

**Comment by nicgirault** [comment]
Nice! Nowaday there is no other way than a link to the repository: https://github.com/nicgirault/circosJS. I would be glad to read your paper if you can give me a link later.

Thanks

**Comment by YulongNiu** [comment]
Thanks @nicgirault. I will at first try to cite the repository link, and will definitely acknowledge your excellent work.
