### ISSUE TITLE
importing for Angular2

### ISSUE THREAD

**Issue by yodafreddan** [nicgirault/circosJS#36]
I'm trying to use circosJS in a Angular2 project but I am struggling with getting it to import. Have installed the library using npm which seem to be successful. Any suggestions/solution?

**Comment by nicgirault** [comment]
Please provide code snippets or more details... I don't see how I can help you with so few details...

**Comment by kevinbatongbakal** [comment]
That's great, since it was D3 based, I guess you have to check on it.
I have question, is it possible in CircoJS to copy the original config
(meaning the layout and plotting) of the original circos?

Thanks for updating your library. that helps us a lot.


Regards,
Kevin

**Comment by nicgirault** [comment]
@yodafreddan the import issue has been fixed in version 2.0.7.
