### ISSUE TITLE
Configuration setting for closing margins

### ISSUE THREAD

**Issue by russellbits** [nicgirault/circosJS#41]
![screenshot2017-08-14](https://user-images.githubusercontent.com/1154056/29296573-0a10ed3c-8110-11e7-85b9-425e4e1c951e.png)
This is the current illustration that I am working on, and I am wondering what the setting is to remove these "longitudinal" margins between the wedges of data. I tried setting 'radialMargin' to 0 but that does not appear to help.

**Comment by nicgirault** [comment]
You have to set the `gap` setting of the layout to 0. I agree it's not obvious. I'll add an example in the doc and add a clearer alias. radialMargin sounds good. Thanks for reporting this

**Comment by russellbits** [comment]
Great! Thanks so much.
