### ISSUE TITLE
onClick callback for tracks to return Datum objects

### ISSUE THREAD

**Issue by yodafreddan** [nicgirault/circosJS#42]
Hi, 
I wonder how I do to hook up a listener to detect a click event, returning datum object in the same way as it is done for the tooltipContent implementation? 

Have managed to detect a click event for the Layout using onClick but it is returning HTML elements and it is not working for any other tracks.

Any suggestions?

best wishes

**Comment by nicgirault** [comment]
@yodafreddan sorry for the delay to answer you issue. I added in version 2.1.0 a configuration attribute in all tracks and layout configuration called `events`.

It allows you to define your own event handlers. For example:

```javascript
{
  events: {
    'click.alert': function (datum, index, nodes, event) {
      window.alert(datum)
    },
    'mouseover.alert': function (datum, index, nodes, event) {
      window.alert(datum)
    }
  }
}
```

**Comment by yodafreddan** [comment]
Thanks for adding this. Appreciated!!

**Comment by yodafreddan** [comment]
Any plans to update the npm release to version 2.1.0 or should I clone the latest git version?

**Comment by nicgirault** [comment]
Sorry, it's published now

**Comment by yodafreddan** [comment]
thanks! I have installed and tested. Have a suggestion to a related enhancement. Would it be possible to add some callback object providing  linking to what track that the clicked datum object belongs to?

Are the click event also implemented for the chords?

Great work!!
