### ISSUE TITLE
Documentation Update: Track Data Formatting

### ISSUE THREAD

**Issue by jacobjmarks** [nicgirault/circosJS#44]
Hi there, after countless hours of trying to get chords rendered (receiving 'No data source at index [0..n-1]' for each array of data given to the track), I found a discrepency after running through the source for the provided demo seen [here](http://nicgirault.github.io/circosJS/demo/).

I found the chord data used in the demo was formatted as objects, seen below:
```
[
    {
        source: {
            id: 'sourceID',
            start: sourceStart,
            end: sourceEnd
        },
        target: {
            id: 'targetID',
            start: targetStart,
            end: targetEnd
        }
    },
[
```
Yet any documentation I found was stating chord data be formatted as arrays:
```
[
    ['sourceID', sourceStart, sourceEnd, 'targetID', targetStart, targetEnd],
]
```
Only after using the object formatting for my data did the chords render without error.
Taking a quick look at the heatmap demo, it would seem the case is the same, data is formatted in objects as opposed to arrays seen in the documentation.

Hoping this can be updated to help out others :)
Thanks.

**Comment by nicgirault** [comment]
Thanks @jacobjmarks for reporting this issue and sorry for the delay to answer. I fixed the documentation and sorry for the inconvenience
