### ISSUE TITLE
Something about line

### ISSUE THREAD

**Issue by rknenuvis** [nicgirault/circosJS#45]
Sorry to bother you.
This is great job. But i have some trouble in working with "line". When i using "fill",i can't change its color,it is always gray.Is that normal? How can i change fill-color?
Thank you.

**Comment by nicgirault** [comment]
Thanks @rknenuvis . I added the missing doc. You should use the fillColor option. I'm sorry for the delay dealing with issues. Although it is important for this project that you report bugs such as this one, you can in addition find answers by yourself by having a look into the source code. Tracks are here https://github.com/nicgirault/circosJS/tree/master/src/tracks. You can see at the top of each file the default configuration.
