### ISSUE TITLE
chords plot relationship file format.

### ISSUE THREAD

**Issue by mictadlo** [nicgirault/circosJS#46]
Hi,
I am interested to  get similar [chords plot](https://github.com/nicgirault/circosJS#chords). I have the following table which shows the relationship between the data 

```
query   | subject     | query  start | query end | subject start | Subject end
Locus_1 | tig00007234 | 1            | 1054      | 140511        | 137383
Locus_1 | tig00007234 | 1            | 1057      | 77478         | 74353
Locus_1 | tig00007234 | 1            | 1057      | 46295         | 43158
```
How should I format the above data to make it compatible to CircosJS?

Thank you in advance,

Michal

**Comment by nicgirault** [comment]
@mictadlo the documentation is here https://github.com/nicgirault/circosJS#chords. Is there something not clear about the formatting?

**Comment by mictadlo** [comment]
Do you have any script which produces this kind of input file for circosJS?
