### ISSUE TITLE
Documentation error in gitbook

### ISSUE THREAD

**Issue by winni2k** [nicgirault/circosJS#48]
When I try to run the initial example given in https://nicgirault.gitbooks.io/circosjs/content/layout.html then I get the error message:
```
circos.js:4483 Uncaught TypeError: Cannot create property 'offset' on number '250'
    at Layout.agg.blocks (circos.js:4483)
    at circos.js:6959
    at circos.js:1845
    at baseForOwn (circos.js:3274)
    at circos.js:3387
    at baseReduce (circos.js:6956)
    at reduce (circos.js:5542)
    at new Layout (circos.js:4482)
    at Core.layout (circos.js:151)
    at circos_test.html:67
```

It looks like perhaps the gitbook is outdated?

One clear discrepancy I find between it and what is in the layout section of the [README.md](https://github.com/nicgirault/circosJS#layout) is the order of the `configuration` and `data` arguments supplied to `instance.layout`:

**gitbook:** `instance.layout(configuration, layout_data);`
**README.md:** `myCircos.layout(data, configuration);`

**Comment by alegomes** [comment]
I found the same.

README.md say "The first argument of the layout function is a configuration object that control the format of the layout." but the layout configuration is the **second** argument.

And, then, "The second argument of the layout function is an array of data that describe the layout regions. " but data is the **first** argument.

**Comment by alegomes** [comment]
And, then, at [1], it's written:

> The first argument is the track name
> The second argument is the heatmap configuration
> The third argument is the data

when, in fact, the correct is:

The second argument is the __data__
The third argument is the **heatmap configuration**

I'm using version 2.0.3, btw.

[]s

[1] https://nicgirault.gitbooks.io/circosjs/content/tracks/heatmap.html

**Comment by nicgirault** [comment]
@winni2k @alegomes the gitbook is deprecated. I'll delete it. You should refer to the README for documentation and examples. Where did you find the link to the gitbook?

**Comment by nicgirault** [comment]
I close the issue since I deleted the gitbook
