### ISSUE TITLE
npm WARN enoent ENOENT: no such file or directory, open '/circos/package.json'

### ISSUE THREAD

**Issue by mictadlo** [nicgirault/circosJS#50]
Hi,

```
npm install --save circos

npm WARN enoent ENOENT: no such file or directory, open '/home/mictadlo/projects/circos/package.json'
npm WARN circos No description
npm WARN circos No repository field.
npm WARN circos No README data
npm WARN circos No license field.
```

What did I miss?

Thank you in advance.

**Comment by nicgirault** [comment]
Where did you write this command? It looks like it is in your project directory and that you didn't initialize npm. To initialize npm: `npm init`. If this was the case you should first learn what is npm (https://www.sitepoint.com/beginners-guide-node-package-manager/) or follow the [installation](https://github.com/nicgirault/circosJS#installation) guide without npm.
