### ISSUE TITLE
Accessibility from one track to another

### ISSUE THREAD

**Issue by MaxiMacko** [nicgirault/circosJS#57]
Hello.

I have a question about how different tracks can interact. For example if I need to change the color of the circular diagram sector after click on the corresponding text on the Text Track. Is it possible to change styles of different tracks via the block_id or in some another way?

Thank you in advance

**Comment by nicgirault** [comment]
Thanks for reporting this use case. I'm not sure you can do it. Did you try to inspect the svg? I guess you can use selectors to get your track, can't you?

**Comment by MaxiMacko** [comment]
I have managed to wire all the tracks via block_id so I would say this issue can be closed. Thanks for the response
